apiVersion: v2
name: rossmann
description: A Helm chart for Rossmann Sales Pipeline - Retail Forecasting MLOps
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - retail-forecasting
  - mlops
  - fastapi
  - dash
maintainers:
  - name: Khaled Saifullah
    email: ksnishaat@gmail.com
