apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rossmann.fullname" . }}-config
data:
  APP_NAME: {{ .Values.env.APP_NAME | quote }}
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  APP_LOG_LEVEL: {{ .Values.env.APP_LOG_LEVEL | quote }}
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER | quote }}
  POSTGRES_DB: {{ .Values.env.POSTGRES_DB | quote }}
  DASH_PORT: {{ .Values.env.DASH_PORT | quote }}