apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "rossmann.fullname" . }}-secrets
data:
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD | default "cm9zYW5kbWV0cnVzdDEyMw==" | b64enc | quote }}